/**
 * One goal per day of the year. Everyone sees the same goal on the same
 * calendar day so Crews can do it together.
 */
export const DAILY_GOALS: readonly string[] = [
  'Post a picture of a frog',
  'Start a Spark at a local coffee shop',
  'Ask your Crew for their go-to karaoke song',
  'Compliment someone in your Crew',
  'Post a photo of the oldest thing in your fridge',
  'Start a Spark for a sunset walk',
  'Send your Crew your most-played song this week',
  'Text a friend you haven\u2019t talked to in a while',
  'Post a picture of a dog you don\u2019t know (ask first)',
  'Start a Spark at a park you\u2019ve never been to',
  'Ask your Crew what their perfect Saturday looks like',
  'Invite someone new to your Crew',
  'Post a photo of your shoes right now',
  'Start a Spark for tacos',
  'Tell your Crew one thing you\u2019re proud of this week',
  'Leave a comment on a Crew post',
  'Post a picture of the sky exactly at noon',
  'Start a Spark to go thrifting',
  'Ask your Crew for a movie recommendation',
  'React \u{1F525} to every post in your Crew today',
  'Post a photo of something purple',
  'Start a Spark at the library',
  'Start a poll in Crew chat about the best pizza topping',
  'Keep every one of your fires lit today',
  'Post a picture of your current view, no cleaning up first',
  'Start a Spark for a late-night diner run',
  'Ask your Crew what their dream vacation is',
  'Join someone else\u2019s Spark',
  'Post a photo of a mailbox with personality',
  'Start a Spark for a pickup game of anything',
  'Share your worst joke in Crew chat',
  'Update your status to what you\u2019re doing right now',
  'Post a picture of the best tree on your street',
  'Start a Spark at a farmers market',
  'Ask your Crew what song describes their week',
  'Buy a coffee for the person behind you in line',
  'Post a photo of your go-to snack',
  'Start a Spark to watch the sunrise',
  'Tell your Crew about the best thing you ate this week',
  'Leave a kind note for a stranger',
  'Post a picture of a cloud that looks like something',
  'Start a Spark for a board game night',
  'Start a poll: mountains or beach?',
  'Tell your Crew a three-word review of your day',
  'Post a photo of a sign with a typo',
  'Start a Spark at the nearest ice cream place',
  'Ask your Crew about their weirdest dream',
  'Pick up five pieces of litter on your walk',
  'Post a picture of your keychain',
  'Start a Spark for a bike ride',
  'Share a childhood memory in Crew chat',
  'Take a walk without your headphones',
  'Post a photo of a cat in a window',
  'Start a Spark to try a restaurant none of you have been to',
  'Ask your Crew what they\u2019d do with a free day tomorrow',
  'Go somewhere you\u2019ve never been in your own town',
  'Post a picture of the weirdest item in your junk drawer',
  'Start a Spark to go stargazing',
  'Send your Crew a GIF that describes your mood',
  'Hold the door for someone',
  'Post a photo of your morning drink',
  'Start a Spark for a picnic',
  'Ask your Crew for a book recommendation',
  'Write a thank-you note to someone',
  'Post a picture of a bird, any bird',
  'Start a Spark at a bookstore',
  'Start a poll: cats or dogs?',
  'Learn a card trick and show your Crew',
  'Post a photo of your favorite mug',
  'Start a Spark for a movie night',
  'Ask your Crew what their comfort show is',
  'Draw a portrait of someone in your Crew and post it',
  'Post a picture of a sunset from wherever you are',
  'Start a Spark for a hike, even a small one',
  'Tell your Crew something they don\u2019t know about you',
  'Cook something new and post the result',
  'Post a photo of something that makes you nostalgic',
  'Start a Spark at a dog park (dog optional)',
  'Ask your Crew what they\u2019re looking forward to',
  'Build a blanket fort and post it',
  'Post a picture of a flower growing somewhere it shouldn\u2019t',
  'Start a Spark to get boba',
  'Start a poll to pick your next hangout spot',
  'Recreate an old photo with your Crew',
  'Post a photo of your desk exactly as it is',
  'Start a Spark for karaoke',
  'Ask your Crew what their hidden talent is',
  'Find the best view within walking distance and post it',
  'Post a picture of a vending machine',
  'Start a Spark at a museum or gallery',
  'Share a fun fact in Crew chat',
  'Wear something bold today and post a fit check',
  'Post a photo of a door you\u2019d love to walk through',
  'Start a Spark to cook dinner together',
  'Ask your Crew about the best advice they\u2019ve gotten',
  'Plant something, even a seed in a cup',
  'Post a picture of your lunch before the first bite',
  'Start a Spark for a study or work session',
  'Start a poll: breakfast for dinner, yes or no?',
  'Call a family member just to say hi',
  'Post a photo of the moon',
  'Start a Spark to go bowling',
  'Ask your Crew what snack they\u2019d bring to a desert island',
  'Get a group photo with your Crew',
  'Post a picture of a squirrel mid-mischief',
  'Start a Spark at a lake, river, or beach',
  'Tell your Crew the last thing that made you laugh',
  'Look for a four-leaf clover and post your best attempt',
  'Post a photo of something shaped like a heart',
  'Start a Spark for breakfast before work or class',
  'Ask your Crew for their go-to coffee order',
  'Make a playlist for your Crew and share it',
  'Post a picture of the last thing you bought',
  'Start a Spark to shoot hoops',
  'Start a poll: early bird or night owl?',
  'Do something nice for a neighbor',
  'Post a photo of a mural or street art',
  'Start a Spark at an arcade',
  'Ask your Crew what they\u2019d name a boat',
  'Take a new route home and post what you find',
  'Post a picture of your reflection in something that isn\u2019t a mirror',
  'Start a Spark to go mini golfing',
  'Share your current phone wallpaper in Crew chat',
  'Shout out your favorite local business in Crew chat',
  'Post a photo of a bug (a cute one, please)',
  'Start a Spark for a donut run',
  'Ask your Crew about their first concert',
  'Bake something and share it with your Crew',
  'Post a picture of your favorite hoodie',
  'Start a Spark to watch the game together',
  'Start a poll: best fast food fries',
  'Write your Crew a haiku',
  'Post a photo of a puddle reflecting the sky',
  'Start a Spark at a record store',
  'Ask your Crew what superpower they\u2019d pick',
  'Learn a word in a new language and teach it to your Crew',
  'Post a picture of the book you\u2019re reading (or should be)',
  'Start a Spark to walk a new neighborhood',
  'Tell your Crew a goal you have this month',
  'Take a photo that looks like an album cover',
  'Post a photo of the smallest thing you own',
  'Start a Spark for a pizza night',
  'Ask your Crew what their walk-up song would be',
  'Make a paper crane and post it',
  'Post a picture of a duck',
  'Start a Spark at a food truck',
  'Start a poll to rank the seasons',
  'Do a 10-minute stretch and tell your Crew',
  'Post a photo of a bench you\u2019d sit on for an hour',
  'Start a Spark for a gym session',
  'Ask your Crew about the best trip they\u2019ve taken',
  'Find something older than you and post it',
  'Post a picture of something red on your walk',
  'Start a Spark to go on a photo walk',
  'Share a song you\u2019ve had on repeat',
  'Take a photo from a bug\u2019s point of view',
  'Post a photo of your hand holding something weird',
  'Start a Spark at a trivia night',
  'Ask your Crew what they\u2019d cook to impress someone',
  'Take a photo from the highest spot you can get to',
  'Post a picture of the first thing you see when you wake up',
  'Start a Spark to grab smoothies',
  'Start a poll: pineapple on pizza?',
  'Order the most random item on a menu',
  'Start a Spark for a bonfire (the real kind)',
  'Ask your Crew what they\u2019d do if they won the lottery',
  'Post a before-and-after of something you cleaned',
  'Post a picture of a leaf bigger than your hand',
  'Start a Spark at a rooftop or scenic overlook',
  'Tell your Crew about a small win today',
  'Do a tiny good deed, then tell your Crew about it',
  'Post a photo of a houseplant (yours or a stranger\u2019s)',
  'Start a Spark to play frisbee',
  'Ask your Crew about their most useless skill',
  'Tip a little extra today',
  'Post a picture of your favorite spot in your home',
  'Start a Spark for a volunteer shift',
  'Start a poll: texting or calling?',
  'Send someone in your Crew a pep talk',
  'Post a photo of a shadow that looks cool',
  'Start a Spark at a bakery',
  'Ask your Crew for their favorite local spot',
  'Start a no-complaining-for-24-hours challenge with your Crew',
  'Post a picture of a horse, cow, goat, or any farm friend',
  'Start a Spark for a late-night drive with good music',
  'Share a photo from this month last year in Crew chat',
  'Share your favorite quote in Crew chat',
  'Post a photo of the most chaotic shelf at the grocery store',
  'Start a Spark to play cards',
  'Ask your Crew what they\u2019d tell their younger self',
  'Spot five different dogs today and report back',
  'Post a picture of a snail',
  'Start a Spark to see live music',
  'Start a poll: sweet or savory breakfast?',
  'Count the birds you see today and tell your Crew',
  'Post a photo of a bike that isn\u2019t yours',
  'Start a Spark at a botanical garden',
  'Ask your Crew which TV show world they\u2019d live in',
  'Take a picture where everything is one color',
  'Post a picture of your pet\u2019s funniest pose (or a friend\u2019s pet)',
  'Start a Spark for a run',
  'Tell your Crew one thing you\u2019re grateful for',
  'Post a photo of something that\u2019s exactly your favorite color',
  'Start a Spark to go to the batting cages',
  'Ask your Crew for a podcast recommendation',
  'Challenge your Crew to a push-up count',
  'Post a picture of a rock you\u2019d skip',
  'Start a Spark at a flea market',
  'Start a poll: best decade for music',
  'Make your bed and post proof',
  'Post a photo of a clock showing 11:11',
  'Start a Spark to try a new cuisine',
  'Ask your Crew what they\u2019d put in a time capsule',
  'Finish a full bottle of water before noon and flex it',
  'Start a Spark to go skating (roller or ice)',
  'Ask your Crew the story behind their name',
  'Wake up 15 minutes early and post the sky',
  'Post a photo of something you\u2019ve had since you were a kid',
  'Start a Spark for a garage sale crawl',
  'Ask your Crew what food they could eat every day',
  'Order a drink you\u2019ve never tried at a coffee shop',
  'Post a picture of a street sign with your initial',
  'Sit somewhere new at lunch',
  'Post a photo of a butterfly or moth',
  'Start a Spark to feed ducks (bring peas, not bread)',
  'Ask your Crew what their spirit animal is',
  'Say hi to a neighbor you\u2019ve never talked to',
  'Post a picture of the fanciest dessert you can find',
  'Start a Spark for a video game session',
  'Tell your Crew about something you learned this week',
  'Send a postcard to someone',
  'Start a Spark at a tea house',
  'Ask your Crew about the best gift they ever got',
  'Find a hidden gem in your town and post it',
  'Post a picture of a cool car in a parking lot',
  'Start a Spark to go fishing',
  'Start a poll: which movie should you all watch next?',
  'Start a Crew-wide step challenge',
  'Post a photo of a pinecone',
  'Start a Spark for a cheap lunch',
  'Ask your Crew what their favorite smell is',
  'Try to make someone laugh today',
  'Start a Spark at a comedy show',
  'Share your go-to recipe in Crew chat',
  'Take a photo that tells a story without words',
  'Post a photo of a lamp with main-character energy',
  'Start a Spark to build a snowman or a sandcastle',
  'Ask your Crew about the scariest thing they\u2019ve done',
  'Post a picture of your Crew\u2019s favorite hangout spot',
  'Post a photo of an animal statue',
  'Start a Spark for a craft night',
  'Start a poll: best holiday of the year',
  'Post a picture of your breakfast, no matter how sad',
  'Start a Spark at a pier or dock',
  'Ask your Crew what their ideal sandwich is',
  'Take a photo through a window',
  'Post a photo of a train, bus, or subway car',
  'Start a Spark to go kayaking or paddleboarding',
  'Ask your Crew what app they couldn\u2019t live without',
  'Post a picture of a balloon',
  'Start a Spark for s\u2019mores',
  'Tell your Crew your unpopular opinion (keep it friendly)',
  'Take a mirror selfie in the weirdest place you can find',
  'Post a photo of something with polka dots',
  'Start a Spark at a local sports game',
  'Ask your Crew who would survive longest in a zombie movie',
  'Do a quick sketch and post it, no matter how it turns out',
  'Post a picture of a wild mushroom (look, don\u2019t eat)',
  'Start a Spark to walk to get coffee, no driving',
  'Start a poll: would you rather fly or be invisible?',
  'Redo your phone home screen and show your Crew',
  'Post a photo of your handwriting',
  'Start a Spark for yoga in the park',
  'Walk into a local shop you\u2019ve never been inside',
  'Post a picture of a fountain',
  'Start a Spark to go to a car show',
  'Share the last photo in your camera roll (if it\u2019s safe)',
  'Cook a new recipe with just five ingredients',
  'Start a Spark at a street fair or festival',
  'Ask your Crew what their favorite childhood cartoon was',
  'Name your houseplant and introduce it to your Crew',
  'Start a Spark to play tennis or pickleball',
  'Start a poll: best ice cream flavor',
  'Do a random act of kindness for someone in your Crew',
  'Start a Spark for a 20-minute walk and talk',
  'Rank your top three snacks in Crew chat',
  'Take a photo with your eyes closed and post whatever you got',
  'Post a picture of the tallest building you can see',
  'Start a Spark to watch a meteor shower',
  'Ask your Crew what they\u2019d want their last meal to be',
  'Find something that rhymes with your name and post it',
  'Post a photo of a lizard, turtle, or anything scaly',
  'Start a Spark at a drive-in or outdoor movie',
  'Tell your Crew what you\u2019d do with an extra hour every day',
  'Get outside for 15 minutes before noon',
  'Post a picture of a hat you\u2019d never wear',
  'Start a Spark to try a new hot sauce together',
  'Start a poll: best board game of all time',
  'Invent a Crew inside joke and use it three times',
  'Post a photo of your screen time report (be brave)',
  'Start a Spark at a pottery or painting class',
  'Ask your Crew what they\u2019re binge-watching',
  'Post a picture of a playground',
  'Start a Spark for a midnight snack run',
  'Ask your Crew what song they\u2019d play at a bonfire',
  'Go screen-free for an hour and tell your Crew how it went',
  'Start a Spark to go climbing',
  'Tell your Crew about a place that feels like home',
  'Take a picture of something you usually walk right past',
  'Start a Spark at a lookout point',
  'Start a poll: best snack for a road trip',
  'Give your Crew a weather forecast for your mood',
  'Start a Spark to plan a group trip',
  'Ask your Crew what their biggest pet peeve is',
  'Relight a fire that\u2019s gone out',
  'Post a picture of your socks',
  'Start a Spark for a homework or reading party',
  'Ask your Crew what they\u2019d be famous for',
  'Post a photo of a tiny door, gnome, or fairy house',
  'Start a Spark to wash your cars together',
  'Start a poll: best way to eat a potato',
  'Invite your Crew to a Spark happening in the next hour',
  'Post a picture of a bridge',
  'Start a Spark at a hole-in-the-wall restaurant',
  'Start a Spark to go to the zoo or aquarium',
  'Tell your Crew the best compliment you\u2019ve ever received',
  'Post a photo of your favorite thing to cook',
  'Post a picture of a boat',
  'Start a Spark to go apple or berry picking',
  'Start a poll: best movie snack',
  'Post a photo of a sticker on a lamppost',
  'Post a picture of something perfectly symmetrical',
  'Start a Spark to watch the rain from a porch',
  'Post a picture of the messiest part of your car',
  'Start a Spark for a dessert crawl',
  'Start a poll: best cereal ever made',
  'Post a picture of a stained-glass window',
  'Tell your Crew what your dream job was as a kid',
  'Post a photo of a dandelion',
  'Start a Spark to learn a dance together',
  'Ask your Crew what they\u2019d do on a perfect rainy day',
  'Post a photo of your favorite local restaurant\u2019s menu',
  'Post a picture of anything rainbow-colored',
  'Start a Spark to sit outside and do nothing together',
  'Post a photo of your workout, even if it\u2019s a walk',
  'Post a picture of a chalk drawing',
  'Start a Spark for a laundromat hang',
  'Post a photo of a building number that means something to you',
  'Post a picture of a pumpkin, squash, or gourd',
  'Start a Spark to watch the city lights come on',
  'Tell your Crew about a song that takes you back',
  'Post a photo of frost, snow, or ice',
  'Post a picture of a cozy corner',
  'Start a Spark for hot chocolate',
  'Post a photo of your oldest photo (a photo of a photo)',
  'Post a picture of a pigeon living its best life',
  'Start a Spark to go window shopping',
  'Ask your Crew what the last thing they Googled was',
  'Post a photo of something that made you laugh today',
  'Post a picture of an outfit you love',
  'Ask your Crew what their favorite thing about the Crew is',
  'Post a photo of the stars, or give it your best try',
  'Post a picture of a bowl of noodles',
  'Tell your Crew your favorite memory together from this year',
  'Post a photo of a tree with its leaves changing',
];

function dayOfYear(date: Date): number {
  const start = new Date(date.getFullYear(), 0, 1);
  const today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
  return Math.round((today.getTime() - start.getTime()) / 86_400_000);
}

/** Local-calendar goal for `date` (Dec 31 of a leap year wraps to the first goal). */
export function goalForDate(date = new Date()): { text: string; day: number } {
  const index = dayOfYear(date) % DAILY_GOALS.length;
  return { text: DAILY_GOALS[index]!, day: index + 1 };
}
